<?php
/**
 * Create by maxime
 * Date 3/5/2020
 * Time 7:44 PM
 * Project :  projet8
 * IDE : PhpStorm
 * FileName : TaskControllerTest.php as TaskControllerTest
 */

namespace Tests\AppBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;
use Tests\AppBundle\AbstractTestController;

class TaskControllerTest extends AbstractTestController
{
    protected function setUp():void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        parent::reloadDataFixtures();
    }

    public function testIndexAction()
    {
        $client = static::createClient();
        $crawler = $client->request('GET', '/tasks');
        $client->followRedirect();

        $this->assertEquals(200, $client->getResponse()->getStatusCode());
    }
}
