# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  AppBundle\:
    resource: '../../src/AppBundle/*'
    # you can exclude directories or files
    # but if a service is unused, it's removed anyway
    exclude: '../../src/AppBundle/{Entity,Repository}'

  AppBundle\Controller\:
    resource: '../../src/AppBundle/Controller'
    tags: ['controller.service_arguments']

  AppBundle\Repository\UserRepository:
    tags:
      - {name: 'user.repository'}

  AppBundle\Repository\TaskRepositoy:
    tags:
      - {name: 'task.repositoy'}

  AppBundle\Entity\User:
    tags:
      - {name: 'user.entity'}

  AppBundle\Entity\Task:
    tags:
      - {name: 'task.entity'}