# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  AppBundle\Controller\:
    resource: '../../src/AppBundle/Controller'
    tags: ['controller.service_arguments']

  AppBundle\Repository\UserRepository:
    tags:
      - {name: 'user.repository'}

  AppBundle\Repository\TaskRepositoy:
    tags:
      - {name: 'task.repositoy'}